IF EXISTS (SELECT NAME FROM SYS.DATABASES WHERE NAME = 'NORTHWIND_METADATA')
BEGIN
	DROP DATABASE NORTHWIND_METADATA
END

GO

CREATE DATABASE NORTHWIND_METADATA
GO

USE NORTHWIND_METADATA
GO

CREATE TABLE ETLExcecution(
	Id INT IDENTITY (1,1) NOT NULL,
	UserName NVARCHAR(50),
	MachineName NVARCHAR (50),
	PackageName NVARCHAR(50),
	ETLLoad DATETIME,
	ETLCountRows BIGINT,
	ETLCountNewRegister BIGINT,
	ETLCountModifiedRegister BIGINT
)